name: 'Setup Bun and cache node_modules'
description: 'Setup Bun and Node.js and cache the node_modules directory'
inputs:
  node_version:
    description: 'Node.js version to use'
    required: false
    default: v22.x
  bun_version:
    description: 'Bun version to use'
    required: false
    default: 1.2.9

runs:
  using: 'composite'
  steps:
    - name: Set up Node ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun_version }}

    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: |
          node_modules
          packages/*/node_modules
          apps/*/node_modules
        key: modules-bun-${{ hashFiles('bun.lockb') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        bun install
        bun run prisma:generate
      env:
        HUSKY: '0'
